services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # container:host. Map the container port 3000 to the host port 3000
    volumes:
      - .:/app # host:container. Mount the host directory ./ to the container directory /app
      - /app/node_modules # prevents the node_modules directory from being overwritten by the volume mount,
      # ensuring that the container uses its own installed dependencies instead of those in the host machine
    environment:
      NODE_ENV: development # Enables hot-reloading, detailed error messages, and development-specific features
      # BACKEND_URL: "http://localhost:8090" # The URL of the backend API. This is the default value, but it may not work in all cases.
      # On macOS/Windows, you can often use http://host.docker.internal:8090 to reach a port on the host machine from inside the container.
      # On Linux, you might need an alternative approach (e.g., use the container name if they share a Docker network, or configure /etc/hosts).
      BACKEND_URL: "http://host.docker.internal:8090"
